package com.tak.repository.entity

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable
import com.tak.rest.resources.UserResource

@DynamoDBTable(tableName = "users")
data class UserEntity (

        @DynamoDBHashKey
        var id: String? = "",

        @DynamoDBAttribute
        var username: String? = "",

        @DynamoDBAttribute
        var password: String? = ""
){
    companion object Factory {
        fun fromResource(resource: UserResource) : UserEntity{
            return UserEntity(resource.id ?: "", resource.username, resource.password)
        }
    }
}